language: java

jdk: oraclejdk8

before_install:
  - sudo apt-get install gradle-5.3
#  - apt-cache search gradle
#  - sudo apt-get install gradle-5.3.1

script: cd micro-service-gradle && gradle clean test