apiVersion: v1
kind: Namespace
metadata:
  name: micro-service
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: micro-service-config
  namespace: micro-service
data:
  JAEGER_UDP_SENDER_HOST: jaeger-agent.istio-system.svc.cluster.local
  REDIS_HOST: redis-master